site_name: SDVX Manual
site_url: https://kfc.arkitosekai.net
theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.instant.progress
    - navigation.sections
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: simple/notion 
      link: https://secrets.arkitosekai.net

nav:
  - Home: 'index.md'
  - HDD: 
    - 部署: 'hdd/setup.md'
    - Asphyxia配置: 'hdd/asphyxia.md'
    - 优化运行性能: 'hdd/optimize.md'
    - 更新: 'hdd/update.md'
    - 进阶配置:
      - 进阶Asphyxia配置: 'hdd/advanced/advanced-asphyxia.md'
      - 安装Mod/omnimix: 'hdd/advanced/layeredfs.md'
      - 降低音频延迟: 'hdd/advanced/audio-api.md'
      - 触摸屏配置: 'hdd/advanced/touchscreen.md'
      - 测试菜单: 'hdd/advanced/testmenu.md'
    - 杂项:
      - 常见问题: 'hdd/extras/troubleshoot.md'
      - Discord RPC与自定义: 'hdd/extras/discord-rpc.md'
      - 店内联机: 'hdd/extras/linkparty.md'
      - 耳机孔配置: 'hdd/extras/enable-headphone-jack.md'
  - 家用版: 
    - 须知: 'konasute/qa.md'
    - 部署: 'konasute/setup.md'
    - 订阅游戏: 'konasute/subscription.md'
    - 曲包: 'konasute/songpack.md'